### ISSUE TITLE
Multimeda Keys of Samsung TV not working

### ISSUE THREAD

**Issue by TimUx** [bramp/libcec-daemon#19]
Hi,
I've compiled/installed libcec 2.1.4 and the libcec-daemon on my rraspberry pi.

Everything seems to work but some multimedia key like stop, play, .. are not working.

when i've started the libcec-daemon with -v option, you can see, that the stop and play button are recognized by the daemon, but no keypress action will be caused.

Here the output of the stop button:

DEBUG - Main::onCecLogMessage(72315 [T]>> 01:42:03)
DEBUG - Main::onCecLogMessage(72316 [D]>> TV (0) -> Recorder 1 (1): deck control (42))
DEBUG - Main::onCecCommand(Command 0->1[  ] 66)

play button:

DEBUG - Main::onCecLogMessage(73585 [T]>> 01:41:24)
DEBUG - Main::onCecLogMessage(73586 [D]>> TV (0) -> Recorder 1 (1): play (41))
DEBUG - Main::onCecCommand(Command 0->1[  ] 65)

and for example some other buttons

DEBUG - Main::onCecLogMessage(21081 [T]>> 01:44:00)
DEBUG - Main::onCecLogMessage(21081 [D]>> TV (0) -> Recorder 1 (1): user control pressed (44))
DEBUG - Main::onCecCommand(Command 0->1[  ] 68)
DEBUG - Main::onCecLogMessage(21082 [D]key pressed: select (0))
DEBUG - Main::onCecKeyPress(Key press: SELECT for 0ms)
DEBUG - send 352
DEBUG - Main::onCecLogMessage(21784 [T]>> 01:8b:00)
DEBUG - Main::onCecLogMessage(21787 [D]>> TV (0) -> Recorder 1 (1): vendor remote button up (8B))
DEBUG - Main::onCecCommand(Command 0->1[  ] 139)
DEBUG - Main::onCecLogMessage(21789 [D]key released: select (0))
DEBUG - Main::onCecKeyPress(Key press: SELECT for 707ms)
DEBUG - release 352

Where can i change something in the source code, so that this button will cause an keypress action?

Regards TimUx

**Comment by julianxhokaxhiu** [comment]
Up, this should be merged! I'm having a Samsung TV too and those buttons are not working atm

**Comment by ircpsycho** [comment]
Hi, I have the some problem whit my samsung TV.
The buttons play, pause and stop not working. In debug i see 
DEBUG - Main::onCecLogMessage(72315 [T]>> 01:42:03)
DEBUG - Main::onCecLogMessage(72316 [D]>> TV (0) -> Recorder 1 (1): deck control (42))
DEBUG - Main::onCecCommand(Command 0->1[ ] 66)

play button:

DEBUG - Main::onCecLogMessage(73585 [T]>> 01:41:24)
DEBUG - Main::onCecLogMessage(73586 [D]>> TV (0) -> Recorder 1 (1): play (41))
DEBUG - Main::onCecCommand(Command 0->1[ ] 65)

But no KeyPress.
Any solution?

Thanks and sorry for my english
