### ISSUE TITLE
[Arch Linux] AUR support?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [bramp/libcec-daemon#24]
Hi,

I've found your project since I would like to integrate it inside my set-top-box made with [Arch Linux ARM](http://archlinuxarm.org/) project over a Raspberry Pi. I know I can use plain `make` and `make install` to compile and install it, but are you planning to provide a [`PKGBUILD`](https://wiki.archlinux.org/index.php/PKGBUILD) file so we can create easily a package on Arch?

Or maybe better, are you going to support your own project on [AUR](https://aur.archlinux.org/)?

Thanks in advice :)

**Comment by bramp** [comment]
I have no plans to support Arch. If you wish to contribute the required
files/instructions then please do.

**Comment by julianxhokaxhiu** [comment]
Ok, I'll make a pull-request when it's done :) Thank you

**Comment by emansom** [comment]
Need this as well, packaged it up and published on the AUR as [libcec-daemon-git](https://aur.archlinux.org/packages/libcec-daemon-git).
