### ISSUE TITLE
libCEC Version 3  Support

### ISSUE THREAD

**Issue by mklooss** [bramp/libcec-daemon#27]
Replace the following items in src/libcec.cpp
https://github.com/bramp/libcec-daemon/blob/master/src/libcec.cpp#L156
``config.iDoubleTapTimeoutMs``
 to
``config.iDoubleTapTimeout50Ms``

and
https://github.com/bramp/libcec-daemon/blob/master/src/libcec.cpp#L141
``config.clientVersion = CEC_CLIENT_VERSION_CURRENT;``
to
``config.clientVersion = LIBCEC_VERSION_CURRENT;``

**Comment by bramp** [comment]
Fixed by 358af036928b85ec39
