### ISSUE TITLE
Raspberry Pi3 - Raspian & Mythfrontend

### ISSUE THREAD

**Issue by mzimmerman** [bramp/libcec-daemon#29]
Since mythfrontend didn't work out of the box for me, I thought I'd try libcec-daemon.  I'm completely new to CEC so bear with me.

Compiling against libcec3 I had to make the following changes:
+//     config.clientVersion = CEC_CLIENT_VERSION_CURRENT;
+//     config.iDoubleTapTimeoutMs = 0;

Compiling then worked like a treat.  Running libcec-daemon in debug mode, I could see 9 buttons were recognized by it all correctly, however when they were translated into uinput events, mythfrontend wouldn't recognize some of them in order to map them to the appropriate function.

Is this configurable?  E.g., my SELECT/ENTER button is detected as SELECT by libcec-daemon, however it sends 352 which mythfrontend doesn't recognize when in the configuration screen.  There are others too.  Is this an odd CEC device or is this something you all have worked around already?

**Comment by bramp** [comment]
Sorry for the lack of response.

Currently the keys aren't configurable, but you can hack the code to change their meaning.

As for the changes for libcec3, thanks for those. I need to protect the code a little as libcec occasionally make incompatible changes like this.

**Comment by bramp** [comment]
Ok the two lines you needed to comment out were fixed by 358af036928b85ec39

**Comment by bramp** [comment]
Adding a custom key map was discussed in #2. Closing this to track efforts there.
