### ISSUE TITLE
Building against libcec >=4.x (P8, Ubuntu 20.04)

### ISSUE THREAD

**Issue by tomm3h** [bramp/libcec-daemon#31]
I realise there have been a number of years since there was any activity to this repo, but if I may document my current woes in attempting to build libcec-daemon against libcec=4.0.4, in an Ubuntu 20.04 (x86_64) environment.

Initially, configure fails on, `$PKG_CONFIG --print-errors --cflags --libs "libcec >= 2.1"`. Runnning this command manually highlights the need to _also_ install packages libp8-platform-dev (which requires libfstrcmp0 & libfstrcmp0-dev) and libudev-dev.

Unfortunately, make then fails in a fashion that I'm not capable of unpicking. My programming prowess isn't up to very much, much less my C++. 

Output from 'make' in the case that it helps, [attached here](https://github.com/bramp/libcec-daemon/files/4672361/libcec-daemon-libcec_4.0.4-teh.txt).

If anyone's still running the daemon out there on an up to date system, please do let me know how you did it. :)

**Comment by matthewbauer** [comment]
This should be fixed in https://github.com/bramp/libcec-daemon/pull/32.

**Comment by tomm3h** [comment]
> This should be fixed in #32.

Cloned from your branch, and it built on my first attempt. Thank you! If you or bramp require any output, please do let me know.
